included:
  - Sonora
  - SonoraLiveActivity

excluded:
  - DerivedData
  - .tmp
  - server
  - SonoraTests
  - SonoraUITests

opt_in_rules:
  # Safety & clarity
  - explicit_acl
  - explicit_top_level_acl
  - implicit_optional_initialization
  - weak_delegate
  - fatal_error_message
  # Styles that reduce diff noise and aid reviews
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_string_enum_value
  - redundant_type_annotation
  - type_contents_order
  - file_types_order
  - file_name
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - indentation_width
  - yoda_condition

analyzer_rules:
  - unused_import
  - explicit_self
  - unused_declaration
  - capture_variable

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

identifier_name:
  allowed_symbols: "_"
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - URL
    - url
    - x
    - y
    - dx
    - dy
    - i
    - j
    - k
    - v
    - d
    - p
    - r
    - e
    - h
    - m
    - s
    - t
    - to
    - up
    - on

type_body_length:
  warning: 350
  error: 800

file_length:
  warning: 800
  error: 1300

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  ignores_urls: true

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 60
  error: 160

nesting:
  type_level:
    warning: 3
    error: 5

indentation_width:
  indentation_width: 4
  include_comments: false

reporter: "markdown"
