included:
  - SonoraTests
  - SonoraUITests

excluded:
  - DerivedData
  - .tmp
  - server

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_string_enum_value
  - redundant_type_annotation
  - type_contents_order
  - file_types_order
  - file_name
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - indentation_width
  - yoda_condition

# Tests: relax ACL pressure
disabled_rules:
  - explicit_top_level_acl

analyzer_rules:
  - unused_import

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

type_body_length:
  warning: 600
  error: 1200

file_length:
  warning: 1200
  error: 2000

line_length:
  warning: 140
  error: 240
  ignores_comments: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  ignores_urls: true

cyclomatic_complexity:
  warning: 14
  error: 28

function_body_length:
  warning: 120
  error: 240

indentation_width:
  indentation_width: 4
  include_comments: false

reporter: "markdown"
